package com.devpulse.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.OffsetDateTime;

/**
 * Entity representing a refresh token stored in the database.
 *
 * <p>A refresh token is an opaque string (UUID x 2) that allows the client
 * to obtain a new access token without re-authenticating.
 * Storing it in the DB enables server-side revocation and rotation.
 *
 * <p>Maps to the {@code refresh_tokens} table in PostgreSQL.
 * Linked to {@link User} in a many-to-one relationship — a user may have
 * multiple historical tokens, but only those with {@code revoked_at IS NULL}
 * and a future {@code expires_at} are considered active.
 */
@Entity
@Table(name = "refresh_tokens")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RefreshToken {

    /** Primary key generated by a PostgreSQL sequence (BIGSERIAL). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User this refresh token belongs to.
     * Loaded lazily. Deleted cascade when the user is removed.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Token value — a random 64-character hex string (2 x UUID without dashes).
     * Unique across the table.
     */
    @Column(nullable = false, unique = true, length = 64)
    private String token;

    /** Token expiry time (default: 7 days from issuance). */
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    /**
     * Timestamp at which the token was revoked, or {@code null} if still valid.
     * Set when the token is rotated on refresh, on logout, on password change,
     * or when token reuse is detected.
     */
    @Column(name = "revoked_at")
    private OffsetDateTime revokedAt;

    /** Issuance timestamp — set automatically, immutable. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Checks whether the token has expired.
     *
     * @return {@code true} if the current time is after {@link #expiresAt}
     */
    public boolean isExpired() {
        return OffsetDateTime.now().isAfter(expiresAt);
    }

    /**
     * Checks whether the token has been revoked.
     *
     * @return {@code true} if {@link #revokedAt} has been set
     */
    public boolean isRevoked() {
        return revokedAt != null;
    }

    /**
     * Checks whether the token is currently usable (not expired and not revoked).
     *
     * @return {@code true} if the token can still be exchanged for an access token
     */
    public boolean isActive() {
        return !isExpired() && !isRevoked();
    }
}
