package com.devpulse.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.OffsetDateTime;

/**
 * Entity representing a refresh token stored in the database.
 *
 * <p>A refresh token is an opaque string (UUID x 2) that allows the client
 * to obtain a new access token without re-authenticating.
 * Storing it in the DB allows server-side revocation.
 *
 * <p>Maps to the {@code refresh_tokens} table in PostgreSQL.
 * Linked to {@link User} in a many-to-one relationship (a user may have
 * multiple refresh tokens; previous ones are revoked on each new login).
 */
@Entity
@Table(name = "refresh_tokens")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RefreshToken {

    /** Primary key generated by a PostgreSQL sequence (BIGSERIAL). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User this refresh token belongs to.
     * Loaded lazily. Deleted cascade when the user is removed.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Token value — a random 64-character hex string (2 x UUID without dashes).
     * Unique across the table.
     */
    @Column(nullable = false, unique = true, length = 64)
    private String token;

    /** Token expiry time (default: 7 days from issuance). */
    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    /** Issuance timestamp — set automatically, immutable. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * Checks whether the token has expired.
     *
     * @return {@code true} if the current time is after {@link #expiresAt}
     */
    public boolean isExpired() {
        return OffsetDateTime.now().isAfter(expiresAt);
    }
}
