package com.devpulse.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;

/**
 * Entity representing a user account in the DevPulse system.
 *
 * <p>Maps to the {@code users} table in PostgreSQL.
 * The password is stored exclusively as a BCrypt hash
 * in the {@code password_hash} column.
 *
 * <p>The user's {@link Role} determines their permissions:
 * <ul>
 *   <li>{@code USER}  — standard permissions (create posts, comments, vote)</li>
 *   <li>{@code ADMIN} — full access, including content moderation</li>
 * </ul>
 */
@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /** Primary key generated by a PostgreSQL sequence (BIGSERIAL). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique username, publicly visible (max 50 characters). */
    @Column(nullable = false, unique = true, length = 50)
    private String username;

    /** Email address — used for account recovery (max 100 characters). */
    @Column(nullable = false, unique = true, length = 100)
    private String email;

    /**
     * BCrypt hash of the password.
     * Never exposed to the client.
     */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * User role defining their permissions.
     * Default value: {@link Role#USER}.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Role role = Role.USER;

    /** Timestamp of account creation — set automatically, immutable. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** Timestamp of the last record update — updated automatically. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
